# docker-compose up
# docker stack deploy --compose-file=docker-stack.yml voting_stack
version: "3"
services:
  webapi2:
    #image: chandrabhan/simpenodeapp
    build: ./
    # networks:
    #   - frontend
    environment:
      - ExtraSettingNotInSettingsFile=Development
    ports:
      - 8010:80
#   nodevideoapp:
#     #image: chandrabhan/simpenodeapp
#     build: ./src/videos/
#     networks:
#       - frontend
#     ports:
#       - 5124:8124
# networks:
#   frontend:
